<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body {
            font-size: 12px;
            color: #111827;
            line-height: 1.5;
        }

        h1, h2, h3 {
            margin: 0 0 8px 0;
        }

        .meta {
            margin-bottom: 18px;
            padding: 12px;
            border: 1px solid #d1d5db;
            border-radius: 8px;
        }

        .section {
            margin-bottom: 18px;
            padding-bottom: 12px;
            border-bottom: 1px solid #e5e7eb;
        }

        .module-card {
            margin-bottom: 12px;
            padding: 10px;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
        }

        .muted {
            color: #6b7280;
        }

        ul {
            margin: 6px 0 0 18px;
        }
    </style>
</head>
<body>
    <h1>Weekly Report - {{ $weeklyReport->project->name }}</h1>
    <div class="meta">
        <div><strong>Report No:</strong> Week {{ $weeklyReport->report_number }}</div>
        <div><strong>Period:</strong> {{ $weeklyReport->period_start->format('d M Y') }} - {{ $weeklyReport->period_end->format('d M Y') }}</div>
        <div><strong>Topic:</strong> {{ $weeklyReport->topic ?? '-' }}</div>
        <div><strong>Status:</strong> {{ strtoupper($weeklyReport->status) }}</div>
        <div><strong>Generated By:</strong> {{ $weeklyReport->generatedBy?->name ?? auth()->user()?->name ?? '-' }}</div>
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <div>{!! nl2br(e($weeklyReport->executive_summary ?? 'No executive summary yet.')) !!}</div>
    </div>

    <div class="section">
        <h2>Progress Overview</h2>
        <p class="muted">Daily reports: {{ $stats['daily_report_count'] }} | Developers: {{ $stats['developer_count'] }} | Modules: {{ $stats['module_count'] }}</p>
        @foreach ($modules as $module)
            <div class="module-card">
                <h3>{{ $module->code }} - {{ $module->name }}</h3>
                <p><strong>Phase:</strong> {{ ucfirst($module->phase) }} | <strong>Status:</strong> {{ ucfirst($module->status) }}</p>

                @foreach ($module->platforms as $platform)
                    <p><strong>{{ $platform->platform_name }}</strong> - {{ $platform->progress_percentage }}%</p>
                    <ul>
                        @forelse ($platform->featureChecklists as $checklist)
                            <li>{{ $checklist->feature_name }} ({{ str_replace('_', ' ', $checklist->status) }})</li>
                        @empty
                            <li class="muted">No checklist items yet.</li>
                        @endforelse
                    </ul>
                @endforeach
            </div>
        @endforeach
    </div>

    <div class="section">
        <h2>Plan of Actions</h2>
        <div>{!! nl2br(e($weeklyReport->plan_of_actions ?? 'No action plan yet.')) !!}</div>
    </div>

    <div class="section">
        <h2>Individual Reports</h2>
        @foreach ($individualSummaries as $item)
            <div class="module-card">
                <h3>{{ $item['user']?->name ?? 'Unknown User' }}</h3>
                <div>{!! nl2br(e($item['summary'])) !!}</div>
            </div>
        @endforeach
    </div>
</body>
</html>
